WebInterface Yes
DefaultLanguage zh
DefaultShared Yes           # 添加的打印机默认共享

# 用 @LOCAL 变量，自动适应当前网段，告别硬编码
<Location />
  Order Allow,Deny
  Allow From @LOCAL
</Location>

<Location /admin>
  AuthType Basic
  AuthClass Anonymous
  Order Allow,Deny
  Allow From @LOCAL
</Location>
