#!/bin/sh /etc/rc.common
START=99
start() {
    /etc/init.d/cupsd start
    /etc/init.d/avahi-daemon start
    /etc/init.d/samba4 start
}
stop() {
    /etc/init.d/cupsd stop
    /etc/init.d/avahi-daemon stop
    /etc/init.d/samba4 stop
}
